name: Run Tests

on:
  push:
    branches: [master, use-github-actions]
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'latest'

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test
